name: RepairShopr to Notion Sync

on:
  workflow_dispatch:  # ✅ enables manual run button
  schedule:
    - cron: '*/15 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
      env:
        RS_API_KEY: ${{ secrets.RS_API_KEY }}
        MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
      run: python repairshopr_pull.py
